create table if not exists container
(
    id   bigint generated by default as identity not null primary key,
    time timestamp without time zone             not null default current_timestamp
);

create table if not exists parameter
(
    id           bigint generated by default as identity not null primary key,
    name         varchar,
    value        decimal,
    container_id bigint                                  not null,
    constraint parameter_container_id foreign key (container_id) references container (id) on delete cascade
);